###############
### WINDOWS ###
###############

# build:
# @echo Construyendo Jugador
# @go build -o bin/jugador.exe jugador.go
# @echo Terminado

# clean:
# @echo Eliminando archivos ejecutables
# @del bin\"*.exe"
# @echo Terminado

# run:
# @echo Iniciando Jugador
# @bin/jugador.exe

# all:
# @echo Construyendo Jugador
# @go build -o bin/jugador.exe jugador.go
# @echo Iniciando Jugador
# @bin/jugador.exe

#############
### LINUX ###
#############

build:
	@echo Construyendo Jugador
	@go build -o bin/jugador jugador.go
	@echo Terminado

clean:
	@echo Eliminando archivos ejecutables
	@rm bin/*
	@echo Terminado

run:
	@echo Iniciando Jugador
	@./bin/jugador

all:
	@echo Construyendo Jugador
	@go build -o bin/jugador jugador.go
	@echo Iniciando Jugador
	@./bin/jugador