// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package namenode

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SendPlaysServiceClient is the client API for SendPlaysService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SendPlaysServiceClient interface {
	SendPlays(ctx context.Context, in *PlaysReq, opts ...grpc.CallOption) (*PlaysResp, error)
}

type sendPlaysServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSendPlaysServiceClient(cc grpc.ClientConnInterface) SendPlaysServiceClient {
	return &sendPlaysServiceClient{cc}
}

func (c *sendPlaysServiceClient) SendPlays(ctx context.Context, in *PlaysReq, opts ...grpc.CallOption) (*PlaysResp, error) {
	out := new(PlaysResp)
	err := c.cc.Invoke(ctx, "/sendPlaysNL.SendPlaysService/SendPlays", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendPlaysServiceServer is the server API for SendPlaysService service.
// All implementations must embed UnimplementedSendPlaysServiceServer
// for forward compatibility
type SendPlaysServiceServer interface {
	SendPlays(context.Context, *PlaysReq) (*PlaysResp, error)
	mustEmbedUnimplementedSendPlaysServiceServer()
}

// UnimplementedSendPlaysServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSendPlaysServiceServer struct {
}

func (UnimplementedSendPlaysServiceServer) SendPlays(context.Context, *PlaysReq) (*PlaysResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPlays not implemented")
}
func (UnimplementedSendPlaysServiceServer) mustEmbedUnimplementedSendPlaysServiceServer() {}

// UnsafeSendPlaysServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SendPlaysServiceServer will
// result in compilation errors.
type UnsafeSendPlaysServiceServer interface {
	mustEmbedUnimplementedSendPlaysServiceServer()
}

func RegisterSendPlaysServiceServer(s grpc.ServiceRegistrar, srv SendPlaysServiceServer) {
	s.RegisterService(&SendPlaysService_ServiceDesc, srv)
}

func _SendPlaysService_SendPlays_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaysReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendPlaysServiceServer).SendPlays(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sendPlaysNL.SendPlaysService/SendPlays",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendPlaysServiceServer).SendPlays(ctx, req.(*PlaysReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SendPlaysService_ServiceDesc is the grpc.ServiceDesc for SendPlaysService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SendPlaysService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sendPlaysNL.SendPlaysService",
	HandlerType: (*SendPlaysServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPlays",
			Handler:    _SendPlaysService_SendPlays_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sendPlaysNL.proto",
}
