// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.0
// source: sendPlaysDN.proto

package dataNode

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JugadasResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JugadasResp) Reset() {
	*x = JugadasResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sendPlaysDN_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JugadasResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JugadasResp) ProtoMessage() {}

func (x *JugadasResp) ProtoReflect() protoreflect.Message {
	mi := &file_sendPlaysDN_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JugadasResp.ProtoReflect.Descriptor instead.
func (*JugadasResp) Descriptor() ([]byte, []int) {
	return file_sendPlaysDN_proto_rawDescGZIP(), []int{0}
}

type JugadasReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Registro string `protobuf:"bytes,1,opt,name=registro,proto3" json:"registro,omitempty"`
}

func (x *JugadasReq) Reset() {
	*x = JugadasReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sendPlaysDN_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JugadasReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JugadasReq) ProtoMessage() {}

func (x *JugadasReq) ProtoReflect() protoreflect.Message {
	mi := &file_sendPlaysDN_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JugadasReq.ProtoReflect.Descriptor instead.
func (*JugadasReq) Descriptor() ([]byte, []int) {
	return file_sendPlaysDN_proto_rawDescGZIP(), []int{1}
}

func (x *JugadasReq) GetRegistro() string {
	if x != nil {
		return x.Registro
	}
	return ""
}

var File_sendPlaysDN_proto protoreflect.FileDescriptor

var file_sendPlaysDN_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x65, 0x6e, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x73, 0x44, 0x4e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x73, 0x44, 0x4e,
	0x22, 0x0d, 0x0a, 0x0b, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x28, 0x0a, 0x0a, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x32, 0x52, 0x0a, 0x0e, 0x4a, 0x75, 0x67,
	0x61, 0x64, 0x61, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x0b, 0x53,
	0x65, 0x6e, 0x64, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x12, 0x17, 0x2e, 0x73, 0x65, 0x6e,
	0x64, 0x50, 0x6c, 0x61, 0x79, 0x73, 0x44, 0x4e, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73,
	0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x73, 0x65, 0x6e, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x73, 0x44,
	0x4e, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0e, 0x5a,
	0x0c, 0x6c, 0x61, 0x62, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sendPlaysDN_proto_rawDescOnce sync.Once
	file_sendPlaysDN_proto_rawDescData = file_sendPlaysDN_proto_rawDesc
)

func file_sendPlaysDN_proto_rawDescGZIP() []byte {
	file_sendPlaysDN_proto_rawDescOnce.Do(func() {
		file_sendPlaysDN_proto_rawDescData = protoimpl.X.CompressGZIP(file_sendPlaysDN_proto_rawDescData)
	})
	return file_sendPlaysDN_proto_rawDescData
}

var file_sendPlaysDN_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sendPlaysDN_proto_goTypes = []interface{}{
	(*JugadasResp)(nil), // 0: sendPlaysDN.JugadasResp
	(*JugadasReq)(nil),  // 1: sendPlaysDN.JugadasReq
}
var file_sendPlaysDN_proto_depIdxs = []int32{
	1, // 0: sendPlaysDN.JugadasService.SendJugadas:input_type -> sendPlaysDN.JugadasReq
	0, // 1: sendPlaysDN.JugadasService.SendJugadas:output_type -> sendPlaysDN.JugadasResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sendPlaysDN_proto_init() }
func file_sendPlaysDN_proto_init() {
	if File_sendPlaysDN_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sendPlaysDN_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JugadasResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sendPlaysDN_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JugadasReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sendPlaysDN_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sendPlaysDN_proto_goTypes,
		DependencyIndexes: file_sendPlaysDN_proto_depIdxs,
		MessageInfos:      file_sendPlaysDN_proto_msgTypes,
	}.Build()
	File_sendPlaysDN_proto = out.File
	file_sendPlaysDN_proto_rawDesc = nil
	file_sendPlaysDN_proto_goTypes = nil
	file_sendPlaysDN_proto_depIdxs = nil
}
