// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pozo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PozoServiceClient is the client API for PozoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PozoServiceClient interface {
	SendMount(ctx context.Context, in *MountReq, opts ...grpc.CallOption) (*MountResp, error)
}

type pozoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPozoServiceClient(cc grpc.ClientConnInterface) PozoServiceClient {
	return &pozoServiceClient{cc}
}

func (c *pozoServiceClient) SendMount(ctx context.Context, in *MountReq, opts ...grpc.CallOption) (*MountResp, error) {
	out := new(MountResp)
	err := c.cc.Invoke(ctx, "/pozo.PozoService/SendMount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PozoServiceServer is the server API for PozoService service.
// All implementations must embed UnimplementedPozoServiceServer
// for forward compatibility
type PozoServiceServer interface {
	SendMount(context.Context, *MountReq) (*MountResp, error)
	mustEmbedUnimplementedPozoServiceServer()
}

// UnimplementedPozoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPozoServiceServer struct {
}

func (UnimplementedPozoServiceServer) SendMount(context.Context, *MountReq) (*MountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMount not implemented")
}
func (UnimplementedPozoServiceServer) mustEmbedUnimplementedPozoServiceServer() {}

// UnsafePozoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PozoServiceServer will
// result in compilation errors.
type UnsafePozoServiceServer interface {
	mustEmbedUnimplementedPozoServiceServer()
}

func RegisterPozoServiceServer(s grpc.ServiceRegistrar, srv PozoServiceServer) {
	s.RegisterService(&PozoService_ServiceDesc, srv)
}

func _PozoService_SendMount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PozoServiceServer).SendMount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pozo.PozoService/SendMount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PozoServiceServer).SendMount(ctx, req.(*MountReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PozoService_ServiceDesc is the grpc.ServiceDesc for PozoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PozoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pozo.PozoService",
	HandlerType: (*PozoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMount",
			Handler:    _PozoService_SendMount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pozo.proto",
}
